#!/bin/bash -ex

#global aliases
echo "alias ll='ls -la'" >> /etc/bash.bashrc

cd /usr/games
git clone --depth=1 https://github.com/MFeldpausch/mineos-node minecraft
cd minecraft
git config core.filemode false
chmod +x generate-sslcert.sh mineos_console.js service.js webui.js
cp mineos.conf /etc/mineos.conf
npm install
ln -s /usr/games/minecraft/mineos_console.js /usr/local/bin/mineos