#!/bin/bash -ex
install()
{
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

sid()
{
    DEBIAN_FRONTEND=noninteractive apt-get -f -y -t sid \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

script -c "curl -sL https://deb.nodesource.com/setup_8.x | bash -" /dev/null
apt-get update
install git
install screen
install rdiff-backup
install nodejs
install openjdk-8-jre
install build-essential